export * from "./header/SideBar";
export * from "./header/SearchBar";
export * from "./header/SearchBar2";
export * from "./footer/Footer";
export * from "./main/MovieCard";
export * from "./Spinner";
export * from "./main/Icons";
export * from "./details/Trailer";
export * from "./details/ModalComponent";
